pipeline:
  docker:
    image: docker
    commands:
      - echo $${MYUSERNAME}
      - echo "run export command"
      - export
      - echo $MYUSERNAME > /tmp/file
      - cat /tmp/file
    secrets: [ myusername ]
  debug:
    image: alpine
    environment:
      MYUSERNAME:
        from_secret: myusername
    commands:
      - export
      - echo $MYUSERNAME
