pipeline:
  run_golang:
    group: build
    image: golang
    commands:
      - go build
      - go test
      
  run_bash:
    group: build
    image: alpine
    commands:
      - myhostname=$(hostname)
      - echo my hostname is ${myhostname} 
      
  slack:
    image: plugins/slack
    channel: system_events
    webhook:
      from_secret: slack_webhook
    when:
      status: [ success, failure ]
