kind: pipeline
name: default

steps:
  - name: test
    image: alpine
    environment:
      MYUSERNAME:
        from_secret: myusername
    commands:
      - echo "echo secret"
      - echo $${MYUSERNAME}
      - echo "run env command"
      - env
      - echo $${MYUSERNAME} > /tmp/file
  - name: publish
    image: plugins/docker
    secrets: [ dockerhub_username, dockerhub_password ]
    settings:
      repo: ruanbekker/dronetest
      tags: latest
      username: 
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
