pipeline:
  docker:
    image: alpine
    secrets: [ myusername ]
    commands:
      - echo $${MYUSERNAME}
      - echo "run export command"
      - export
      - echo $MYUSERNAME > /tmp/file
      - cat /tmp/file
