pipeline:
  backend:
    group: build
    image: golang
    commands:
      - go build
      - go test
  frontend:
    group: build
    image: node
    commands:
      - npm install
      - npm run test
      - npm run build
  slack:
    image: plugins/slack
    channel: system_events
    webhook:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
